version: '3.8'

services:
  # Backend service
  backend:
    image: aminseifi/prompt-manager-backend:latest
    container_name: prompt-manager-backend
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
      - ./backend/static:/app/static
      - ./backend/templates:/app/templates
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      sh -c "chmod +x /app/init.sh && 
             /app/init.sh"
    restart: unless-stopped
    networks:
      - prompt-network

  # Database service
  db:
    image: postgres:15-alpine
    container_name: prompt-manager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - prompt-network

  # Frontend service with Apache
  frontend:
    build:
      image: aminseifi/prompt-manager-frontend:latest
    container_name: prompt-manager-frontend
    ports:
      - "8001:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://prompt-back.aminseifi.com/api
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_USE_MOCK_DATA=false
    restart: unless-stopped
    networks:
      - prompt-network

volumes:
  postgres_data:

networks:
  prompt-network:
    driver: bridge 