# Generated by Django 5.0.1 on 2025-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='variables_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema defining the variables used in the template', verbose_name='Variables Schema'),
        ),
    ]
