name: Deploy Prompt Management System

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          
      - name: Set up test environment
        run: |
          cd backend
          echo "SECRET_KEY='django-test-key-super-secret-123'" > .env
          echo "DEBUG=False" >> .env
          echo "POSTGRES_DB=test_db" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_HOST=localhost" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "CI=True" >> .env
          
      - name: Run tests
        run: |
          cd backend
          export CI=True
          export SECRET_KEY='django-test-key-super-secret-123'
          export POSTGRES_HOST=localhost
          export POSTGRES_PORT=5432
          export POSTGRES_DB=test_db
          export POSTGRES_USER=postgres
          export POSTGRES_PASSWORD=postgres
          python manage.py test
          
  build-and-deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Check if required secrets are available
      - name: Check deployment prerequisites
        id: check_deployment
        run: |
          missing=()
          [[ -z "$DOCKER_USERNAME" ]] && missing+=("DOCKER_HUB_USERNAME")
          [[ -z "$DOCKER_PASSWORD" ]] && missing+=("DOCKER_HUB_TOKEN")
          [[ -z "${{ secrets.SERVER_HOST }}" ]] && missing+=("SERVER_HOST")
          [[ -z "${{ secrets.SERVER_USERNAME }}" ]] && missing+=("SERVER_USERNAME")
          [[ -z "${{ secrets.SERVER_SSH_KEY }}" ]] && missing+=("SERVER_SSH_KEY")
          
          if [[ ${#missing[@]} -gt 0 ]]; then
            echo "::warning::Missing secrets: ${missing[*]}"
            echo "can_deploy=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "can_deploy=true" >> $GITHUB_OUTPUT
          
      # Login to Docker Hub
      - name: Login to Docker Hub
        if: steps.check_deployment.outputs.can_deploy == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        if: steps.check_deployment.outputs.can_deploy == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/prompt-manager-backend:latest

      # Deploy to server
      - name: Deploy to server
        if: steps.check_deployment.outputs.can_deploy == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            # Pull the latest docker-compose file from your repository
            wget -O docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml
            
            # Create the .env file from secrets
            mkdir -p backend
            cat > backend/.env << EOL
            # Django environment variables
            SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY || 'django-insecure-default-key-do-not-use-in-production' }}
            DEBUG=${{ secrets.DEBUG || 'False' }}
            
            # Database settings
            POSTGRES_DB=${{ secrets.POSTGRES_DB || 'prompt_db' }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER || 'postgres' }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD || 'postgres' }}
            POSTGRES_HOST=db
            POSTGRES_PORT=5432
            
            # Superuser credentials
            DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME || 'admin' }}
            DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL || 'admin@example.com' }}
            DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD || 'admin_password' }}
            EOL
            
            # Pull the latest images and restart the containers
            docker-compose pull
            docker-compose up -d 